name: PowerHour
version: 1.1.1
author: bittiez
main: US.bittiez.PowerHour.main
depend: [WorldGuard, WorldEdit]
commands:
    PowerHour:
        description: Various PowerHour commands.
        usage: /PowerHour
        permission: PowerHour.PowerHour
permissions:
    PowerHour.PowerHour:
        description: Usage of various PowerHour commands
        default: op
    PowerHour.reload:
        description: Reload config files
        default: op
    PowerHour.addArena:
        description: Allows adding new arena where you are standing
        default: op
    PowerHour.delArena:
        description: Allows deleting arenas
        default: op
    PowerHour.listArenas:
        description: Allows listing all arenas
        default: op
    PowerHour.checkArenas:
        description: Allows checking what arena you are standing in(If any at all)
        default: op
    PowerHour.startPowerHour:
        description: Allows forcing a power hour to start
        default: op
    PowerHour.onJoinMessage:
        description: Will recieve the playerJoin message when logging into the server if they have this permission
        default: op